"""empty message

Revision ID: 8efd8606820a
Revises: 
Create Date: 2023-11-10 02:38:07.464754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8efd8606820a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('imdb_id', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('genre', sa.TEXT(), nullable=True),
    sa.Column('director', sa.TEXT(), nullable=False),
    sa.Column('country', sa.TEXT(), nullable=False),
    sa.Column('imdb_rating', sa.FLOAT(), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=False),
    sa.UniqueConstraint('imdb_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    # ### end Alembic commands ###
